---
driver:
  name: vagrant
  # Mount local /Users/amanly/chef-kits folder as /mnt/share on the VM
  synced_folders:
  - ["/Users/amanly/chef-kits", "/mnt/share", "disabled: false"]

provisioner:
  name: chef_solo
  # Download and install this exact version of chef-client
  require_chef_omnibus: 12.3.0
  # Use the local chef-client rpm specified in install_chef_rpm.sh: 
  chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes 
    audit_mode: :disabled

platforms:
  - name: centos6
    driver:
      box: "opscode-centos-6.6"
      # see available box urls here: https://opscode-vm-bento.s3.amazonaws.com/
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
      # Use the default host-only network along the NAT one. Makes life easier from a networking perspective
      network:
      - ["private_network", {ip: "192.168.56.45"}]

suites:
  - name: default
    run_list:
      - recipe[manage-mysql-db::default]

